spring:
  datasource:
    url: jdbc:h2:mem:mydb
    # url: jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: mk
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
